Repository TheBastionBot/BastionBotDocs, pull requests merged in 2018-08, with the labels that each got.

#7 Added docs for Heroku
  docs/install-heroku.md
Labels: Documentation, Platform Documentation

#8 Implement mkdocs 1 & mkdocs-material 3
  docs/dev.md
  docs/home.md
  mkdocs.yml
  requirements.txt
Labels: enhancement

#9 Updated documentation with the latest working method to host Bastion on glitch.com!
  docs/install-glitch.md
Labels: Documentation
